In [18]:
import pandas as pd

# 1. Load dataset
df = pd.read_csv('imdb_top_1000.csv')

# 2. Select relevant features
selected_features = ['Series_Title', 'Genre', 'Director', 
                    'Overview', 'IMDB_Rating']

movies_df = df[selected_features].copy()

# 3. Handle missing values
# Drop rows with missing values in critical fields
movies_df.dropna(subset=['Series_Title', 'Genre', 'Director', 
                         'Overview', 'IMDB_Rating'], 
                inplace=True)

# 4. Clean text data
def clean_text(text):
    if isinstance(text, str):
        return text.lower().strip()
    return text

# Apply cleaning to text columns
text_columns = ['Series_Title', 'Genre', 'Director','Overview']

for col in text_columns:
    movies_df[col] = movies_df[col].apply(clean_text)

# Select final columns
final_columns = ['Series_Title', 'Genre', 'Director', 
                'Overview', 'IMDB_Rating']

movies_df = movies_df[final_columns]

In [6]:
def movies_you_might_like(title) -> dict:
    if title and len(title) >= 4:
        title_filter =movies_df['Series_Title'].str.contains(title, case=False,na=False)
        matched_movies = movies_df[title_filter]
        if matched_movies.empty:
            return {'error': 'No movies found with that title try to use the movie genre'}
        #getting genres from the first matching movie
        input_movie = matched_movies.iloc[0]
        input_genre = set(input_movie['Genre'].split(', '))
        
        other_movies = movies_df[~title_filter].copy()
        other_movies['genres_overlap']= other_movies['Genre'].apply(
            lambda x:len(set(x.split(', ')) & input_genre))
        recommendations = other_movies[other_movies['genres_overlap'] >0]
        # recommendations = recommendations.sort_values(
        #     by=['genres_overlap', 'IMDB_Rating'],
        #     ascending=[False, False]
        # )
        return{
            'movies you might like': recommendations[['Series_Title', 'Genre',]].to_dict("records")
        }
movies_you_might_like('coco')

{'movies you might like': [{'Series_Title': 'the lord of the rings: the return of the king',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'inception', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'the lord of the rings: the fellowship of the ring',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'the lord of the rings: the two towers',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'star wars: episode v - the empire strikes back',
   'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'interstellar', 'Genre': 'adventure, drama, sci-fi'},
  {'Series_Title': 'sen to chihiro no kamikakushi',
   'Genre': 'animation, adventure, family'},
  {'Series_Title': 'star wars', 'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'shichinin no samurai',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': "it's a wonderful life", 'Genre': 'drama, family, fantasy'},
  {'Series_Title': 'gladiator', 'Genre': 'action, adventure, drama'},
  {'Series_Title': 'the lion king', 'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'hotaru no haka', 'Genre': 'animation, drama, war'},
  {'Series_Title': 'back to the future', 'Genre': 'adventure, comedy, sci-fi'},
  {'Series_Title': 'modern times', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'kimi no na wa.', 'Genre': 'animation, drama, fantasy'},
  {'Series_Title': 'spider-man: into the spider-verse',
   'Genre': 'animation, action, adventure'},
  {'Series_Title': 'avengers: endgame', 'Genre': 'action, adventure, drama'},
  {'Series_Title': 'avengers: infinity war',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'the dark knight rises', 'Genre': 'action, adventure'},
  {'Series_Title': 'taare zameen par', 'Genre': 'drama, family'},
  {'Series_Title': 'wall·e', 'Genre': 'animation, adventure, family'},
  {'Series_Title': 'mononoke-hime', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'raiders of the lost ark', 'Genre': 'action, adventure'},
  {'Series_Title': 'babam ve oglum', 'Genre': 'drama, family'},
  {'Series_Title': 'inglourious basterds', 'Genre': 'adventure, drama, war'},
  {'Series_Title': 'bacheha-ye aseman', 'Genre': 'drama, family, sport'},
  {'Series_Title': 'toy story', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'aliens', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'star wars: episode vi - return of the jedi',
   'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'das boot', 'Genre': 'adventure, drama, thriller'},
  {'Series_Title': '2001: a space odyssey', 'Genre': 'adventure, sci-fi'},
  {'Series_Title': 'lawrence of arabia',
   'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'north by northwest',
   'Genre': 'adventure, mystery, thriller'},
  {'Series_Title': 'the kid', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'klaus', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'queen', 'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'up', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'chak de! india', 'Genre': 'drama, family, sport'},
  {'Series_Title': 'toy story 3', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'batman begins', 'Genre': 'action, adventure'},
  {'Series_Title': 'hauru no ugoku shiro',
   'Genre': 'animation, adventure, family'},
  {'Series_Title': 'indiana jones and the last crusade',
   'Genre': 'action, adventure'},
  {'Series_Title': 'tonari no totoro', 'Genre': 'animation, family, fantasy'},
  {'Series_Title': 'sholay', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'monty python and the holy grail',
   'Genre': 'adventure, comedy, fantasy'},
  {'Series_Title': 'the great escape', 'Genre': 'adventure, drama, history'},
  {'Series_Title': 'the treasure of the sierra madre',
   'Genre': 'adventure, drama, western'},
  {'Series_Title': 'the gold rush', 'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'koe no katachi', 'Genre': 'animation, drama, family'},
  {'Series_Title': 'soul', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'the grand budapest hotel',
   'Genre': 'adventure, comedy, crime'},
  {'Series_Title': 'ôkami kodomo no ame to yuki',
   'Genre': 'animation, drama, fantasy'},
  {'Series_Title': 'inside out', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'song of the sea', 'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'mad max: fury road', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'harry potter and the deathly hallows: part 2',
   'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': "hachi: a dog's tale", 'Genre': 'biography, drama, family'},
  {'Series_Title': 'mary and max', 'Genre': 'animation, comedy, drama'},
  {'Series_Title': 'how to train your dragon',
   'Genre': 'animation, action, adventure'},
  {'Series_Title': 'into the wild', 'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'finding nemo', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'monsters, inc.', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'shin seiki evangelion gekijô-ban: air/magokoro wo, kimi ni',
   'Genre': 'animation, action, drama'},
  {'Series_Title': 'lagaan: once upon a time in india',
   'Genre': 'adventure, drama, musical'},
  {'Series_Title': 'jurassic park', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'stand by me', 'Genre': 'adventure, drama'},
  {'Series_Title': 'kaze no tani no naushika',
   'Genre': 'animation, adventure, fantasy'},
  {'Series_Title': 'fitzcarraldo', 'Genre': 'adventure, drama'},
  {'Series_Title': 'barry lyndon', 'Genre': 'adventure, drama, history'},
  {'Series_Title': 'ben-hur', 'Genre': 'adventure, drama, history'},
  {'Series_Title': 'kakushi-toride no san-akunin',
   'Genre': 'adventure, drama'},
  {'Series_Title': 'the bridge on the river kwai',
   'Genre': 'adventure, drama, war'},
  {'Series_Title': 'le salaire de la peur',
   'Genre': 'adventure, drama, thriller'},
  {'Series_Title': 'the general', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'togo', 'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'bajrangi bhaijaan', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'the martian', 'Genre': 'adventure, drama, sci-fi'},
  {'Series_Title': 'zootopia', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'kaguyahime no monogatari',
   'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'wonder', 'Genre': 'drama, family'},
  {'Series_Title': 'guardians of the galaxy',
   'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'the revenant', 'Genre': 'action, adventure, drama'},
  {'Series_Title': 'deadpool', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'the avengers', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'persepolis', 'Genre': 'animation, biography, drama'},
  {'Series_Title': 'blood diamond', 'Genre': 'adventure, drama, thriller'},
  {'Series_Title': 'g.o.r.a.', 'Genre': 'adventure, comedy, sci-fi'},
  {'Series_Title': 'ratatouille', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'casino royale', 'Genre': 'action, adventure, thriller'},
  {'Series_Title': 'pirates of the caribbean: the curse of the black pearl',
   'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'big fish', 'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': 'the incredibles', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'pâfekuto burû', 'Genre': 'animation, crime, mystery'},
  {'Series_Title': 'the iron giant', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'kôkaku kidôtai', 'Genre': 'animation, action, crime'},
  {'Series_Title': 'the nightmare before christmas',
   'Genre': 'animation, family, fantasy'},
  {'Series_Title': 'aladdin', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'beauty and the beast',
   'Genre': 'animation, family, fantasy'},
  {'Series_Title': 'dances with wolves', 'Genre': 'adventure, drama, western'},
  {'Series_Title': 'akira', 'Genre': 'animation, action, sci-fi'},
  {'Series_Title': 'the princess bride',
   'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'tenkû no shiro rapyuta',
   'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'jaws', 'Genre': 'adventure, thriller'},
  {'Series_Title': 'fiddler on the roof', 'Genre': 'drama, family, musical'},
  {'Series_Title': 'planet of the apes', 'Genre': 'adventure, sci-fi'},
  {'Series_Title': 'the sound of music', 'Genre': 'biography, drama, family'},
  {'Series_Title': 'the wizard of oz', 'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'isle of dogs', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'hunt for the wilderpeople',
   'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'thor: ragnarok', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'star wars: episode vii - the force awakens',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'x-men: days of future past',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'edge of tomorrow', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'star trek', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'letters from iwo jima',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'the fall', 'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': 'life of pi', 'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': 'fantastic mr. fox',
   'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'iron man', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'harry potter and the prisoner of azkaban',
   'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'ying xiong', 'Genre': 'action, adventure, history'},
  {'Series_Title': 'cowboy bebop: tengoku no tobira',
   'Genre': 'animation, action, crime'},
  {'Series_Title': 'children of men', 'Genre': 'adventure, drama, sci-fi'},
  {'Series_Title': 'almost famous', 'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'toy story 2', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'mimi wo sumaseba', 'Genre': 'animation, drama, family'},
  {'Series_Title': 'jûbê ninpûchô', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'a christmas story', 'Genre': 'comedy, family'},
  {'Series_Title': 'the blues brothers', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'dawn of the dead', 'Genre': 'action, adventure, horror'},
  {'Series_Title': 'la montaña sagrada', 'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': 'amarcord', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'aguirre, der zorn gottes',
   'Genre': 'action, adventure, biography'},
  {'Series_Title': 'the wild bunch', 'Genre': 'action, adventure, western'},
  {'Series_Title': 'spartacus', 'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'the ten commandments', 'Genre': 'adventure, drama'},
  {'Series_Title': 'the searchers', 'Genre': 'adventure, drama, western'},
  {'Series_Title': 'miracle on 34th street', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'the adventures of robin hood',
   'Genre': 'action, adventure, romance'},
  {'Series_Title': 'king kong', 'Genre': 'adventure, horror, sci-fi'},
  {'Series_Title': 'paddington 2', 'Genre': 'adventure, comedy, family'},
  {'Series_Title': 'kubo and the two strings',
   'Genre': 'animation, action, adventure'},
  {'Series_Title': 'rogue one', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'captain america: civil war',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'loving vincent', 'Genre': 'animation, biography, crime'},
  {'Series_Title': 'big hero 6', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'english vinglish', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'kaze tachinu', 'Genre': 'animation, biography, drama'},
  {'Series_Title': 'toy story 4', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'how to train your dragon 2',
   'Genre': 'animation, action, adventure'},
  {'Series_Title': 'captain phillips', 'Genre': 'adventure, biography, crime'},
  {'Series_Title': 'the hobbit: the desolation of smaug',
   'Genre': 'adventure, fantasy'},
  {'Series_Title': 'the hobbit: an unexpected journey',
   'Genre': 'adventure, fantasy'},
  {'Series_Title': 'avatar', 'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'apocalypto', 'Genre': 'action, adventure, drama'},
  {'Series_Title': 'veer-zaara', 'Genre': 'drama, family, musical'},
  {'Series_Title': 'tôkyô goddofâzâzu',
   'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'serenity', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'diarios de motocicleta',
   'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'les triplettes de belleville',
   'Genre': 'animation, comedy, drama'},
  {'Series_Title': 'the count of monte cristo',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'waking life', 'Genre': 'animation, drama, fantasy'},
  {'Series_Title': 'wo hu cang long', 'Genre': 'action, adventure, fantasy'},
  {'Series_Title': 'cast away', 'Genre': 'adventure, drama, romance'},
  {'Series_Title': 'october sky', 'Genre': 'biography, drama, family'},
  {'Series_Title': 'shrek', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'the sandlot', 'Genre': 'comedy, drama, family'},
  {'Series_Title': 'batman: mask of the phantasm',
   'Genre': 'animation, action, crime'},
  {'Series_Title': 'majo no takkyûbin',
   'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'back to the future part ii',
   'Genre': 'adventure, comedy, sci-fi'},
  {'Series_Title': 'predator', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'the goonies', 'Genre': 'adventure, comedy, family'},
  {'Series_Title': 'the right stuff', 'Genre': 'adventure, biography, drama'},
  {'Series_Title': 'e.t. the extra-terrestrial', 'Genre': 'family, sci-fi'},
  {'Series_Title': 'the man who would be king',
   'Genre': 'adventure, history, war'},
  {'Series_Title': 'la planète sauvage', 'Genre': 'animation, sci-fi'},
  {'Series_Title': 'willy wonka & the chocolate factory',
   'Genre': 'family, fantasy, musical'},
  {'Series_Title': 'my fair lady', 'Genre': 'drama, family, musical'},
  {'Series_Title': 'mary poppins', 'Genre': 'comedy, family, fantasy'},
  {'Series_Title': 'red river', 'Genre': 'action, adventure, drama'},
  {'Series_Title': 'to have and have not',
   'Genre': 'adventure, comedy, film-noir'},
  {'Series_Title': 'stagecoach', 'Genre': 'adventure, drama, western'},
  {'Series_Title': 'bringing up baby', 'Genre': 'comedy, family, romance'},
  {'Series_Title': 'deadpool 2', 'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'mission: impossible - fallout',
   'Genre': 'action, adventure, thriller'},
  {'Series_Title': 'omoide no mânî', 'Genre': 'animation, drama, family'},
  {'Series_Title': 'kingsman: the secret service',
   'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'captain america: the winter soldier',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'nebraska', 'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'wreck-it ralph', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'le petit prince', 'Genre': 'animation, adventure, drama'},
  {'Series_Title': 'the lego movie', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'star trek into darkness',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'x: first class', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'skyfall', 'Genre': 'action, adventure, thriller'},
  {'Series_Title': 'harry potter and the deathly hallows: part 1',
   'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'gake no ue no ponyo',
   'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'papurika', 'Genre': 'animation, drama, fantasy'},
  {'Series_Title': 'toki o kakeru shôjo',
   'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'tangled', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'harry potter and the goblet of fire',
   'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'coraline', 'Genre': 'animation, drama, family'},
  {'Series_Title': 'vampire hunter d: bloodlust',
   'Genre': 'animation, action, fantasy'},
  {'Series_Title': 'o brother, where art thou?',
   'Genre': 'adventure, comedy, crime'},
  {'Series_Title': 'interstate 60: episodes of the road',
   'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'south park: bigger, longer & uncut',
   'Genre': 'animation, comedy, fantasy'},
  {'Series_Title': 'the fifth element', 'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'a little princess', 'Genre': 'drama, family, fantasy'},
  {'Series_Title': 'the muppet christmas carol',
   'Genre': 'comedy, drama, family'},
  {'Series_Title': 'the last of the mohicans',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'kurenai no buta', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'who framed roger rabbit',
   'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'star trek ii: the wrath of khan',
   'Genre': 'action, adventure, sci-fi'},
  {'Series_Title': 'first blood', 'Genre': 'action, adventure'},
  {'Series_Title': 'rupan sansei: kariosutoro no shiro',
   'Genre': 'animation, adventure, family'},
  {'Series_Title': 'deliverance', 'Genre': 'adventure, drama, thriller'},
  {'Series_Title': 'where eagles dare', 'Genre': 'action, adventure, war'},
  {'Series_Title': 'the dirty dozen', 'Genre': 'action, adventure, war'},
  {'Series_Title': 'goldfinger', 'Genre': 'action, adventure, thriller'},
  {'Series_Title': 'the magnificent seven',
   'Genre': 'action, adventure, western'},
  {'Series_Title': 'the african queen', 'Genre': 'adventure, drama, romance'},
  {'Series_Title': 'fantasia', 'Genre': 'animation, family, fantasy'},
  {'Series_Title': 'the peanut butter falcon',
   'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'guardians of the galaxy vol. 2',
   'Genre': 'action, adventure, comedy'},
  {'Series_Title': 'incredibles 2', 'Genre': 'animation, action, adventure'},
  {'Series_Title': 'moana', 'Genre': 'animation, adventure, comedy'},
  {'Series_Title': 'dawn of the planet of the apes',
   'Genre': 'action, adventure, drama'},
  {'Series_Title': 'kari-gurashi no arietti',
   'Genre': 'animation, adventure, family'},
  {'Series_Title': 'despicable me', 'Genre': 'animation, comedy, crime'},
  {'Series_Title': 'celda 211', 'Genre': 'action, adventure, crime'},
  {'Series_Title': 'zombieland', 'Genre': 'adventure, comedy, fantasy'},
  {'Series_Title': 'sherlock holmes', 'Genre': 'action, adventure, mystery'},
  {'Series_Title': 'stardust', 'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'the secret of kells',
   'Genre': 'animation, adventure, family'},
  {'Series_Title': 'harry potter and the half-blood prince',
   'Genre': 'action, adventure, family'},
  {'Series_Title': 'finding neverland', 'Genre': 'biography, drama, family'},
  {'Series_Title': 'batoru rowaiaru', 'Genre': 'action, adventure, drama'},
  {'Series_Title': "harry potter and the sorcerer's stone",
   'Genre': 'adventure, family, fantasy'},
  {'Series_Title': 'mulan', 'Genre': 'animation, adventure, family'},
  {'Series_Title': 'fear and loathing in las vegas',
   'Genre': 'adventure, comedy, drama'},
  {'Series_Title': 'die hard: with a vengeance',
   'Genre': 'action, adventure, thriller'},
  {'Series_Title': 'dead man', 'Genre': 'adventure, drama, fantasy'},
  {'Series_Title': 'apollo 13', 'Genre': 'adventure, drama, history'},
  {'Series_Title': 'omohide poro poro', 'Genre': 'animation, drama, romance'},
  {'Series_Title': 'home alone', 'Genre': 'comedy, family'},
  {'Series_Title': 'the little mermaid',
   'Genre': 'animation, family, fantasy'},
  {'Series_Title': 'mad max 2', 'Genre': 'action, adventure, sci-fi'},

# Data Preparation Practice Tasks  

## 1. **Data Inspection & Profiling**  
- Load the dataset and display the first 10 rows  
- Check data types of all columns using `.dtypes`  
- Generate summary statistics with `.describe(include='all')`  
- Identify columns with missing values using `.isnull().sum()`  

## 2. **Handling Duplicates**  
- Find duplicate rows using `.duplicated().sum()`  
- Remove duplicates while keeping the first occurrence  
- Verify the dataset size before/after deduplication  

## 3. **Missing Value Treatment**  
- Fill missing directors with "Unknown"  
- Drop rows with missing runtime values  
- Impute missing genres using the mode  
- Fill missing Meta_scores with column median  

## 4. **Outlier Detection & Correction**  
- Identify movies with IMDB_Rating > 10 or < 0  
- Handle invalid runtimes (e.g., "999 min", "10hrs")  
- Use boxplots to detect outliers in `No_of_Votes`  
- Correct negative/invalid Gross values  

## 5. **Format Standardization**  
### Runtime:  
- Extract numeric values (e.g., "100 mins" → 100)  
- Convert to integer and standardize to minutes  

### Year:  
- Remove "(re-release)" and other suffixes  
- Convert to 4-digit integer (e.g., "1998 Original" → 1998)  

### Votes:  
- Remove commas and "K" abbreviations (e.g., "1.5K" → 1500)  
- Convert to integer  

### Meta_score:  
- Remove "/10" suffix and convert to numeric  

### Gross:  
- Remove "$", "USD", and commas  
- Convert to numeric (handle "million" as 1,000,000)  

## 6. **Categorical Data Handling**  
- Normalize genre capitalization (e.g., "drama" → "Drama")  
- Correct typos in genres (e.g., "Dramaa" → "Drama")  
- Standardize certificates (e.g., "PG13" → "PG-13")  
- One-hot encode certificate categories  

## 7. **Data Type Conversion**  
- Convert Runtime, Year, Votes, Meta_score, and Gross to numeric types  
- Ensure Genre and Certificate are categorical types  

## 8. **Complex Pattern Handling**  
- Parse mixed-format runtimes (e.g., "2h30m" → 150)  
- Handle currency conversions (e.g., "€2.5M" → 2,500,000)  

## 9. **Final Validation**  
- Check for remaining missing values  
- Verify no invalid ratings (0 ≤ IMDB_Rating ≤ 10)  
- Ensure all runtime values are reasonable (30 ≤ Runtime ≤ 300)  
- Confirm standardized date formats

data=pd.read_csv("")

In [47]:
#selecting 10 rows
modified_csv = pd.read_csv('modified_imdb_top_1000.csv')
#below here type your code...
specific_rows = df.iloc[[0,1,2,3,4,5,6,7,8,9,]]
specific_rows

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
5,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,The Lord of the Rings: The Return of the King,2003,U,201 min,"Action, Adventure, Drama",8.9,Gandalf and Aragorn lead the World of Men agai...,94.0,Peter Jackson,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1642758,"377,845,905"
6,https://m.media-amazon.com/images/M/MV5BNGNhMD...,Pulp Fiction,1994,A,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",94.0,Quentin Tarantino,John Travolta,Uma Thurman,Samuel L. Jackson,Bruce Willis,1826188,"107,928,762"
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,A,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,"96,898,818"
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,"292,576,195"
9,https://m.media-amazon.com/images/M/MV5BMmEzNT...,Fight Club,1999,A,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,66.0,David Fincher,Brad Pitt,Edward Norton,Meat Loaf,Zach Grenier,1854740,"37,030,102"

In [34]:
#checking the data type
modified_csv = pd.read_csv('modified_imdb_top_1000.csv')
modified_csv.dtypes

Poster_Link       object
Series_Title      object
Released_Year     object
Certificate       object
Runtime           object
Genre             object
IMDB_Rating      float64
Overview          object
Meta_score        object
Director          object
Star1             object
Star2             object
Star3             object
Star4             object
No_of_Votes       object
Gross             object
dtype: object

In [48]:
modified_csv.describe(include='all')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
count,1010,1010,1010,908,1006,1003,1010.000000,1010,845,1000,1010,1010,1010,1010,1010,840
unique,1000,999,303,19,142,204,NaN,1000,201,542,660,841,891,939,999,835
top,https://m.media-amazon.com/images/M/MV5BYmJhZm...,Drishyam,2014,U,101 min,Drama,NaN,Desperate measures are taken by a man who trie...,800.0%,Alfred Hitchcock,Tom Hanks,Emma Watson,Samuel L. Jackson,Michael Caine,31K,"$739,478"
freq,2,3,23,235,25,84,NaN,2,13,14,12,7,5,5,3,2
mean,NaN,NaN,NaN,NaN,NaN,NaN,7.987030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.893041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,7.900000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,8.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,15.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
#modified_csv.dropna(inplace=True)
modified_csv.isnull().sum()
#modified_csv.size

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      102
Runtime            4
Genre              7
IMDB_Rating        0
Overview           0
Meta_score       165
Director          10
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            170
dtype: int64

In [46]:
modified_csv.duplicated().sum()
modified_csv.drop_duplicates(subset='Series_Title', keep='first')
modified_csv.size
# display(len(modified_csv))

11376

Fill missing directors with "Unknown"
Drop rows with missing runtime values
Impute missing genres using the mode
Fill missing Meta_scores with column median

In [54]:
 modified_csv['Runtime'].isnull().sum()

np.int64(0)

In [51]:
# Fill missing values in the 'directors' column with 'Unknown'
modified_csv['Director']=modified_csv['Director'].fillna("Unknown")

# Save the updated CSV file
modified_csv.to_csv("modified_imdb_top_1000.csv", index=False)
#modified_csv.query("Director=='Unknown'",inplace=True)
#modified_csv

In [57]:
modified_csv['Genre'].isnull().sum()

np.int64(0)

In [53]:
modified_csv=modified_csv.dropna(subset=['Runtime'])
modified_csv.to_csv("modified_imdb_top_1000.csv", index=False)

In [58]:
#Impute missing genres using the mode
mode_genre = modified_csv['Genre'].mode()[0]  # mode() returns a list, so we take the first value

# Fill missing values with the mode
modified_csv['Genre'].fillna(mode_genre, inplace=True)

In [63]:
modified_csv['Meta_score'].isnull().sum()

np.int64(0)

In [62]:

# Step 1: Clean the Meta_score column (removing non-numeric characters)
modified_csv['Meta_score'] = modified_csv['Meta_score'].replace(r'[^0-9.]', '', regex=True)

# Step 2: Convert to numeric type
modified_csv['Meta_score'] = pd.to_numeric(modified_csv['Meta_score'], errors='coerce')

# Step 3: Find the median
median_meta_score = modified_csv['Meta_score'].median()

# Step 4: Fill missing values with the median
modified_csv['Meta_score'] = modified_csv['Meta_score'].fillna(median_meta_score)

4. Outlier Detection & Correction
   1. Identify movies with IMDB_Rating > 10 or < 0
   2. Handle invalid runtimes (e.g., "999 min", "10hrs")
   3. Use boxplots to detect outliers in No_of_Votes
   4. Correct negative/invalid Gross values

In [ ]:
modified_csv